Models/Evenement.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SportData.Models
{
    [Table("evenement")]
    public class Evenement
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }

        [Column("libelle")]
        public string Libelle { get; set; }

        [Column("idorganisation")]
        [DisplayName("organisation")]
        public int IdOrganisation { get; set; }

        [Column("datedebut")]
        public DateTime DateDebut { get; set; }

        [Column("datefin")]
        public DateTime DateFin { get; set; }

        [ForeignKey("IdOrganisation")]
        public virtual Organisation? Organisation { get; set; }
    }
}

Controllers/EvenementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SportData.Data;
using SportData.Models;

namespace SportData.Controllers
{
    public class EvenementController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EvenementController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Evenement
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Evenement.Include(e => e.Organisation);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Evenement/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evenement = await _context.Evenement
                .Include(e => e.Organisation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evenement == null)
            {
                return NotFound();
            }

            return View(evenement);
        }

        // GET: Evenement/Create
        public IActionResult Create()
        {
            ViewData["IdOrganisation"] = new SelectList(_context.Organisation, "Id", "Nom");
            return View();
        }

        // POST: Evenement/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Libelle,IdOrganisation,DateDebut,DateFin")] Evenement evenement)
        {
            if (ModelState.IsValid)
            {
                _context.Add(evenement);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdOrganisation"] = new SelectList(_context.Organisation, "Id", "Nom", evenement.IdOrganisation);
            return View(evenement);
        }

        // GET: Evenement/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evenement = await _context.Evenement.FindAsync(id);
            if (evenement == null)
            {
                return NotFound();
            }
            ViewData["IdOrganisation"] = new SelectList(_context.Organisation, "Id", "Nom", evenement.IdOrganisation);
            return View(evenement);
        }

        // POST: Evenement/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Libelle,IdOrganisation,DateDebut,DateFin")] Evenement evenement)
        {
            if (id != evenement.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(evenement);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EvenementExists(evenement.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdOrganisation"] = new SelectList(_context.Organisation, "Id", "Nom", evenement.IdOrganisation);
            return View(evenement);
        }

        // GET: Evenement/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evenement = await _context.Evenement
                .Include(e => e.Organisation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evenement == null)
            {
                return NotFound();
            }

            return View(evenement);
        }

        // POST: Evenement/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var evenement = await _context.Evenement.FindAsync(id);
            if (evenement != null)
            {
                _context.Evenement.Remove(evenement);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EvenementExists(int id)
        {
            return _context.Evenement.Any(e => e.Id == id);
        }
    }
}

Controllers/EvenementSpecController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SportData.Data;
using SportData.Models;
using System.Diagnostics;

namespace SportData.Controllers
{
    public class EvenementSpecController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EvenementSpecController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Details(int id)
        {
            List<SpecificiteEvenement> liste = _context.SpecificiteEvenement
                .Include(a => a.Sport)
                .Include(a => a.Evenement)
                .Where(a => a.IdEvenement == id)
                .ToList();
            ViewData["detailevenement"] = liste;

            ViewBag.Evenement = _context.Evenement.FirstOrDefault(a => a.Id == id).Libelle;

            return View();
        }
    }
}

Views/Evenement/Create.cshtml
@model SportData.Models.Evenement

@{
    ViewData["Title"] = "Créer";
}

<h1>Créer</h1>

<h4>Événement</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Libelle" class="control-label"></label>
                <input asp-for="Libelle" class="form-control" />
                <span asp-validation-for="Libelle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdOrganisation" class="control-label"></label>
                <select asp-for="IdOrganisation" class="form-control" asp-items="ViewBag.IdOrganisation"></select>
            </div>
            <div class="form-group">
                <label asp-for="DateDebut" class="control-label"></label>
                <input asp-for="DateDebut" class="form-control" />
                <span asp-validation-for="DateDebut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateFin" class="control-label"></label>
                <input asp-for="DateFin" class="form-control" />
                <span asp-validation-for="DateFin" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Créer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Evenement/Delete.cshtml
@model SportData.Models.Evenement

@{
    ViewData["Title"] = "Supprimer";
}

<h1>Supprimer</h1>

<h3>Êtes-vous sûr de vouloir supprimer ceci ?</h3>
<div>
    <h4>Événement</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Libelle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateDebut)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateDebut)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateFin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Organisation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Organisation.Id)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Supprimer" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à la liste</a>
    </form>
</div>

Views/Evenement/Details.cshtml
@model SportData.Models.Evenement

@{
    ViewData["Title"] = "Détails";
}

<h1>Détails</h1>

<div>
    <h4>Événement</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Libelle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Libelle)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateDebut)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateDebut)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateFin)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Organisation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Organisation.Nom)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Modifier</a> |
    <a asp-action="Index">Retour à la liste</a>
</div>

Views/Evenement/Edit.cshtml
@model SportData.Models.Evenement

@{
    ViewData["Title"] = "Modifier";
}

<h1>Modifier</h1>

<h4>Événement</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Libelle" class="control-label"></label>
                <input asp-for="Libelle" class="form-control" />
                <span asp-validation-for="Libelle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdOrganisation" class="control-label"></label>
                <select asp-for="IdOrganisation" class="form-control" asp-items="ViewBag.IdOrganisation"></select>
                <span asp-validation-for="IdOrganisation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateDebut" class="control-label"></label>
                <input asp-for="DateDebut" class="form-control" />
                <span asp-validation-for="DateDebut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateFin" class="control-label"></label>
                <input asp-for="DateFin" class="form-control" />
                <span asp-validation-for="DateFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sauvegarder" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Evenement/Index.cshtml
@model IEnumerable<SportData.Models.Evenement>

@{
    ViewData["Title"] = "Index";
}

<h1>Événement</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Créer un nouvel événement</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Libelle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateDebut)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateFin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Organisation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Libelle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateDebut)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateFin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Organisation.Nom)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Modifier</a> |
                    <a asp-action="Details" asp-controller="EvenementSpec" asp-route-id="@item.Id" class="btn btn-sm btn-info">Détails</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Supprimer</a>
                </td>
            </tr>
        }
    </tbody>
</table>